package com.natwest.Transaction.Models;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;

@Entity
public class Transaction {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)

    private int transactionID;  // autogenerated
    private String fromAccountNumber;  // provided by user
    private String toAccountNumber;  // provided by user

    private String toAccountHolderName; //provided by user

    private String type;  // provided by use
    // can be either savings/merchant - if savings to primary its savings else merchant

    private double amountToMerchant; // provided by user
    private double amountToSavings; // generated based on the amountToMerchant
    private String description; // provided by user
    private LocalDate date; // generated automatically

    private LocalTime time;

    private String userEmail;


    // If type is merchant no need to send amountToSavings it will be automatically generated
    public Transaction(String fromAccountNumber, String toAccountNumber, String toAccountHolderName, String type, double amountToMerchant, String description, String userEmail) {
        this.fromAccountNumber = fromAccountNumber;
        this.toAccountNumber = toAccountNumber;
        this.toAccountHolderName = toAccountHolderName;
        this.type = type;
        this.amountToMerchant = amountToMerchant;
        this.description = description;
        this.userEmail = userEmail;

    }


    //If type is savings, send both amountToMerchant and amountToSavings, but make amountToMerchant as 0
    public Transaction(String fromAccountNumber, String toAccountNumber, String toAccountHolderName, String type, double amountToMerchant, double amountToSavings, String description, String userEmail) {
        this.fromAccountNumber = fromAccountNumber;
        this.toAccountNumber = toAccountNumber;
        this.toAccountHolderName = toAccountHolderName;
        this.type = type;
        this.amountToMerchant = 0;
        this.amountToSavings = amountToSavings;
        this.description = description;
        this.userEmail = userEmail;

    }

    public Transaction() {
    }

    public Transaction(int transactionID, String fromAccountNumber, String toAccountNumber, String toAccountHolderName, String type, double amountToMerchant, double amountToSavings, String description, LocalDate date, LocalTime time) {
        this.transactionID = transactionID;
        this.fromAccountNumber = fromAccountNumber;
        this.toAccountNumber = toAccountNumber;
        this.toAccountHolderName = toAccountHolderName;
        this.type = type;
        this.amountToMerchant = amountToMerchant;
        this.amountToSavings = amountToSavings;
        this.description = description;
        this.date = date;
        this.time = time;
    }

    public LocalTime getTime() {
        return time;
    }

    public void setTime(LocalTime time) {
        this.time = time;
    }

    public int getTransactionID() {
        return transactionID;
    }

    public void setTransactionID(int transactionID) {
        this.transactionID = transactionID;
    }

    public String getFromAccountNumber() {
        return fromAccountNumber;
    }

    public void setFromAccountNumber(String fromAccountNumber) {
        this.fromAccountNumber = fromAccountNumber;
    }

    public String getToAccountNumber() {
        return toAccountNumber;
    }

    public void setToAccountNumber(String toAccountNumber) {
        this.toAccountNumber = toAccountNumber;
    }

    public String getToAccountHolderName() {
        return toAccountHolderName;
    }

    public void setToAccountHolderName(String toAccountHolderName) {
        this.toAccountHolderName = toAccountHolderName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public double getAmountToMerchant() {
        return amountToMerchant;
    }

    public void setAmountToMerchant(double amountToMerchant) {
        this.amountToMerchant = amountToMerchant;
    }

    public double getAmountToSavings() {
        return amountToSavings;
    }

    public void setAmountToSavings(double amountToSavings) {
        this.amountToSavings = amountToSavings;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getDate() {
        return date;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    @Override
    public String toString() {
        return "Transaction{" +
                "transactionID=" + transactionID +
                ", fromAccountNumber='" + fromAccountNumber + '\'' +
                ", toAccountNumber='" + toAccountNumber + '\'' +
                ", toAccountHolderName='" + toAccountHolderName + '\'' +
                ", type='" + type + '\'' +
                ", amountToMerchant=" + amountToMerchant +
                ", amountToSavings=" + amountToSavings +
                ", description='" + description + '\'' +
                ", date=" + date +
                ", time=" + time +
                '}';
    }

}

